#requires -Version 7.0
<#
.SYNOPSIS
    Regenerate the embedded IEEE OUI table (oui.tsv) for Thopter.Discovery.

.DESCRIPTION
    Downloads (or reads local copies of) IEEE's own public MA-L, MA-M and MA-S
    registry CSVs and flattens them into a compact tab-separated file:

        <ASSIGNMENT-HEX>\t<Organization Name>

    The assignment length encodes the block size (6 nibbles = MA-L /24,
    7 = MA-M /28, 9 = MA-S /36); OuiDatabase does longest-prefix matching on it.

    Source: https://standards-oui.ieee.org/  (public IEEE datasets, license-clean —
    NOT the Wireshark 'manuf' file, to keep the repo dependency/license story simple).

.PARAMETER SourceDir
    If supplied, read mal.csv/mam.csv/mas.csv from here instead of downloading.

.PARAMETER OutputPath
    Where to write oui.tsv. Defaults to the embedded-resource location.

.EXAMPLE
    ./Update-Oui.ps1
    ./Update-Oui.ps1 -SourceDir ./raw -OutputPath ../../src/Thopter.Discovery/Oui/oui.tsv
#>
[CmdletBinding()]
param(
    [string]$SourceDir,
    [string]$OutputPath = (Join-Path $PSScriptRoot '..' '..' 'src' 'Thopter.Discovery' 'Oui' 'oui.tsv')
)

$ErrorActionPreference = 'Stop'

$sources = @(
    @{ Name = 'MA-L'; File = 'mal.csv'; Url = 'https://standards-oui.ieee.org/oui/oui.csv' }
    @{ Name = 'MA-M'; File = 'mam.csv'; Url = 'https://standards-oui.ieee.org/oui28/mam.csv' }
    @{ Name = 'MA-S'; File = 'mas.csv'; Url = 'https://standards-oui.ieee.org/oui36/oui36.csv' }
)

$work = if ($SourceDir) { $SourceDir } else { Join-Path ([System.IO.Path]::GetTempPath()) "thopter-oui-$([guid]::NewGuid().ToString('N'))" }
if (-not (Test-Path $work)) { New-Item -ItemType Directory -Path $work -Force | Out-Null }

$entries = [System.Collections.Generic.Dictionary[string,string]]::new([StringComparer]::Ordinal)

foreach ($src in $sources) {
    $path = Join-Path $work $src.File
    if (-not (Test-Path $path)) {
        Write-Host "Downloading $($src.Name) from $($src.Url) ..."
        Invoke-WebRequest -Uri $src.Url -OutFile $path -UserAgent 'Thopter-OUI-build' -MaximumRetryCount 3 -RetryIntervalSec 5
    }

    $rows = Import-Csv -Path $path
    foreach ($row in $rows) {
        $assignment = ($row.Assignment ?? '').Trim().ToUpperInvariant()
        $vendor = ($row.'Organization Name' ?? '').Trim()
        if ($assignment.Length -in 6, 7, 9 -and $vendor.Length -gt 0) {
            # Collapse internal whitespace/tabs so the TSV stays one field per line.
            $vendor = ($vendor -replace '\s+', ' ')
            $entries[$assignment] = $vendor
        }
    }
    Write-Host "  $($src.Name): $($rows.Count) rows"
}

$sorted = $entries.Keys | Sort-Object
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("# IEEE OUI table for Thopter.Discovery — generated by tools/update-oui/Update-Oui.ps1")
[void]$sb.AppendLine("# Format: <ASSIGNMENT-HEX>\t<Organization Name>  (6/7/9 nibbles = MA-L/MA-M/MA-S)")
foreach ($key in $sorted) {
    [void]$sb.Append($key).Append("`t").AppendLine($entries[$key])
}

$dir = Split-Path -Parent $OutputPath
if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }

$utf8NoBom = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText($OutputPath, $sb.ToString(), $utf8NoBom)

Write-Host "Wrote $($entries.Count) OUI records to $OutputPath"
